config/routes.rb
Rails.application.routes.draw do
  resources :chapters

  resources :syllabuses

  resources :courses

  devise_for :users

  root 'syllabuses#index'

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :syllabus
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_one :syllabus

  accepts_nested_attributes_for :syllabus
end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
  has_many :chapters
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :full_name, :role) }
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @chapters = Chapter.all
    respond_with(@chapters)
  end

  def show
    respond_with(@chapter)
  end

  def new
    @chapter = Chapter.new
    respond_with(@chapter)
  end

  def edit
  end

  def create
    @chapter = Chapter.new(chapter_params)
    @chapter.save
    respond_with(@chapter)
  end

  def update
    @chapter.update(chapter_params)
    respond_with(@chapter)
  end

  def destroy
    @chapter.destroy
    respond_with(@chapter)
  end

  private
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    def chapter_params
      params.require(:chapter).permit(:name, :description, :syllabus_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    @course.syllabus = Syllabus.new
    respond_with(@course)
  end

  def edit
  end

  def create
    puts "PARAMS---------#{course_params.inspect}"
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :short_form, syllabus_attributes: [:id, :name, :description, :course_id])
    end
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController
  before_action :set_syllabus, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @syllabuses = Syllabus.all
    respond_with(@syllabuses)
  end

  def show
    respond_with(@syllabus)
  end

  def new
    @syllabus = Syllabus.new
    respond_with(@syllabus)
  end

  def edit
  end

  def create
    @syllabus = Syllabus.new(syllabus_params)
    @syllabus.save
    respond_with(@syllabus)
  end

  def update
    @syllabus.update(syllabus_params)
    respond_with(@syllabus)
  end

  def destroy
    @syllabus.destroy
    respond_with(@syllabus)
  end

  private
    def set_syllabus
      @syllabus = Syllabus.find(params[:id])
    end

    def syllabus_params
      params.require(:syllabus).permit(:name, :description, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/views/chapters/_form.html.erb
<%= simple_form_for(@chapter) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Chapter</h3>
        </div>
        <div class="panel-body">
          <form role="form">
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, autofocus: true, :class => "form-control", :placeholder => "Name" %>
            </div>

            <div class="form-group">
              <label>Description</label>
              <%= f.text_field :description, :class => "form-control", :placeholder => "Description" %>
            </div>

            <div class="form-group">
              <label>Course</label><br>
			  <%= f.select :syllabus_id, Syllabus.all.map { |r| [r.name, r.id] }, :class => "form-control", :prompt => '-- Select --' %>
            </div>

            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%= f.button :submit, "Create", :class => "btn btn-success btn-block" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
<% end %>

app/views/chapters/edit.html.erb
<h2 class="page-header">Edit Chapter
  <div class="pull-right">
    <%= link_to 'Back', chapters_path, :class => "btn btn-warning" %>
  </div>
</h2>

<%= render 'form' %>

app/views/chapters/index.html.erb
<h2 class="page-header">Chapters
  <div class="pull-right">
    <%= link_to 'New Chapter', new_chapter_path, :class => "btn btn-warning" %>
  </div>
</h2>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Syllabus</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @chapters.each do |chapter| %>
        <tr>
          <td><%= chapter.name %></td>
          <td><%= chapter.description %></td>
          <% name = Syllabus.find(chapter.syllabus_id).name %>
          <td><%= name %></td>
          <td><%= link_to 'Show', chapter %></td>
          <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
          <td><%= link_to 'Destroy', chapter, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/chapters/new.html.erb
<h2 class="page-header">New Chapter
  <div class="pull-right">
    <%= link_to 'Back', chapters_path, :class => "btn btn-warning" %>
  </div>
</h2>

<%= render 'form' %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="page-header">Chapter Detail
  <div class="pull-right">
    <%= link_to 'Back', chapters_path, :class => "btn btn-warning" %>
  </div>
</h2>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Chapter</h3>
    </div>
    <div class="panel-body">
      <form role="form">
        <div class="form-group">
          <label>Name : </label>
          <%= @chapter.name %>
        </div>

        <div class="form-group">
          <label>Description : </label>
          <%= @chapter.description %>
        </div>

        <div class="form-group">
          <label>Syllabus : </label>
          <% name = Syllabus.find(@chapter.syllabus_id).name %>
          <%= name %>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
    <%= f.error_notification %>
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Course</h3>
        </div>
        <div class="panel-body">
          <form role="form">
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, autofocus: true, :class => "form-control", :placeholder => "Name" %>
            </div>

            <div class="form-group">
              <label>Description</label>
              <%= f.text_field :description, :class => "form-control", :placeholder => "Description" %>
            </div>

            <div class="form-group">
              <label>Short Form</label>
              <%= f.text_field :short_form, :class => "form-control", :placeholder => "Short Form" %>
            </div>

            <%= f.simple_fields_for :syllabus do |p| %>
                <div class="form-group">
                  <label>Syllabus Name</label>
                  <%= p.text_field :name, :class => "form-control", :placeholder => "Name" %>
                </div>

                <div class="form-group">
                  <label>Syllabus Description</label>
                  <%= p.text_field :description, :class => "form-control", :placeholder => "Description" %>
                </div>
            <% end %>

            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%= f.button :submit, "Create", :class => "btn btn-success btn-block" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
<% end %>

app/views/courses/edit.html.erb
<h2 class="page-header">Edit Course
  <div class="pull-right">
    <%= link_to 'Back', courses_path, :class => "btn btn-warning" %>
  </div>
</h2>

<%= render 'form' %>

app/views/courses/index.html.erb
<h2 class="page-header">Courses
  <div class="pull-right">
    <%= link_to 'New Course', new_course_path, :class => "btn btn-warning" %>
  </div>
</h2>

<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Short form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.short_form %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/courses/new.html.erb
<h2 class="page-header">New Course
  <div class="pull-right">
    <%= link_to 'Back', courses_path, :class => "btn btn-warning" %>
  </div>
</h2>

<%= render 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="page-header">Course Detail
  <div class="pull-right">
    <%= link_to 'Back', courses_path, :class => "btn btn-warning" %>
  </div>
</h2>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Course</h3>
    </div>
    <div class="panel-body">
      <form role="form">
        <div class="form-group">
          <label>Name : </label>
          <%= @course.name %>
        </div>

        <div class="form-group">
          <label>Description : </label>
          <%= @course.description %>
        </div>

        <div class="form-group">
          <label>Short Form : </label>
          <%= @course.short_form %>
        </div>

        <div class="form-group">
          <label>Syllabus Name : </label>
          <%= @course.syllabus.name %>
        </div>

        <div class="form-group">
          <label>Syllabus Description : </label>
          <%= @course.syllabus.description %>
        </div>
      </form>
    </div>
  </div>
</div>

<%#= link_to 'Edit', edit_course_path(@course) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneStopAcademicDetail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style type="text/css">
      .projectTitle{
          font-size:20px;padding-left:15px;padding-top:10px;
      }
  </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle projectToggle" data-toggle="collapse" data-target=".navbar-collapse" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="projectTitle"><span style="color:#F7A11A">OneStop</span><span style="color:#fff">Education</span></p>
    </div>
    <% if current_user %>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/courses">Courses</a></li>
            <li><a href="/syllabuses">Syllabus</a></li>
            <li><a href="/chapters">Chapters</a></li>
            <li><a href="/users">Students</a></li>
            <li><a href="/sign_out"><span>Logout</span></a></li>
          </ul>
        </div>
    <% end %>
  </div>
</div>
<div class="container" style="margin-top: 5%">
  <%= yield %>
</div>

</body>
</html>

app/views/syllabuses/_form.html.erb
<%= simple_form_for(@syllabus) do |f| %>
  <%= f.error_notification %>
  <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Syllabus</h3>
        </div>
        <div class="panel-body">
          <form role="form">
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, autofocus: true, :class => "form-control", :placeholder => "Name" %>
            </div>

            <div class="form-group">
              <label>Description</label>
              <%= f.text_field :description, :class => "form-control", :placeholder => "Description" %>
            </div>

            <div class="form-group">
              <label>Course</label><br>
              <%#= f.text_field :course_id, :class => "form-control", :placeholder => "Short Form" %>
			        <%= f.select :course_id, Course.all.map { |r| [r.name, r.id] }, :class => "form-control", :prompt => '-- Select --' %>
            </div>

            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%= f.button :submit, "Create", :class => "btn btn-success btn-block" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
<% end %>

app/views/syllabuses/edit.html.erb
<h2 class="page-header">Edit Syllabus
  <div class="pull-right">
    <%= link_to 'Back', syllabuses_path, :class => "btn btn-warning" %>
  </div>
</h2>

<%= render 'form' %>

app/views/syllabuses/index.html.erb
<h2 class="page-header">Syllabuses
  <div class="pull-right">
    <%= link_to 'New Syllabus', new_syllabus_path, :class => "btn btn-warning" %>
  </div>
</h2>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @syllabuses.each do |syllabus| %>
        <tr>
          <td><%= syllabus.name %></td>
          <td><%= syllabus.description %></td>
          <% name = Course.find(syllabus.course_id).name %>
          <td><%= name %></td>
          <td><%= link_to 'Show', syllabus %></td>
          <td><%= link_to 'Edit', edit_syllabus_path(syllabus) %></td>
          <td><%= link_to 'Destroy', syllabus, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/syllabuses/new.html.erb
<h2 class="page-header">New Syllabus
  <div class="pull-right">
    <%= link_to 'Back', syllabuses_path, :class => "btn btn-warning" %>
  </div>
</h2>

<%= render 'form' %>

app/views/syllabuses/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="page-header">Syllabus Detail
  <div class="pull-right">
    <%= link_to 'Back', syllabuses_path, :class => "btn btn-warning" %>
  </div>
</h2>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Syllabus</h3>
    </div>
    <div class="panel-body">
      <form role="form">
        <div class="form-group">
          <label>Name : </label>
          <%= @syllabus.name %>
        </div>

        <div class="form-group">
          <label>Description : </label>
          <%= @syllabus.description %>
        </div>

        <div class="form-group">
          <label>Course : </label>
          <% name = Course.find(@syllabus.course_id).name %>
          <%= name %>
        </div>
      </form>
    </div>
  </div>
</div>



<%#= link_to 'Edit', edit_syllabus_path(@syllabus) %>
<%#= link_to 'Back', syllabuses_path %>